/****************************************************************************
**
** Metadata for VideoInsertOcxLib generated by dumpcpp v5.9.0 using
** dumpcpp.exe {4C178A86-3798-47A6-9617-D18CD613CC0C}
** from the type library C:\WINDOWS\SysWow64\VideoInsertOcx.ocx
**
****************************************************************************/

#define QAX_DUMPCPP_VIDEOINSERTOCXLIB_NOINLINES
#include "videoinsertocxlib.h"

using namespace VideoInsertOcxLib;

struct qt_meta_stringdata_all_t {
    QByteArrayData data[23];
    char stringdata0[257];
};
#define QT_MOC_LITERAL(idx, ofs, len, table) \
    Q_STATIC_BYTE_ARRAY_DATA_HEADER_INITIALIZER_WITH_OFFSET(len, \
    offsetof(qt_meta_stringdata_all_t, stringdata##table) + ofs \
        - idx * sizeof(QByteArrayData) \
    )
static const qt_meta_stringdata_all_t qt_meta_stringdata_all = {
    {
QT_MOC_LITERAL(0, 0, 35, 0),
QT_MOC_LITERAL(1, 36, 9, 0),
QT_MOC_LITERAL(2, 46, 0, 0),
QT_MOC_LITERAL(3, 47, 4, 0),
QT_MOC_LITERAL(4, 52, 6, 0),
QT_MOC_LITERAL(5, 59, 4, 0),
QT_MOC_LITERAL(6, 64, 4, 0),
QT_MOC_LITERAL(7, 69, 15, 0),
QT_MOC_LITERAL(8, 85, 4, 0),
QT_MOC_LITERAL(9, 90, 6, 0),
QT_MOC_LITERAL(10, 97, 4, 0),
QT_MOC_LITERAL(11, 102, 4, 0),
QT_MOC_LITERAL(12, 107, 8, 0),
QT_MOC_LITERAL(13, 116, 7, 0),
QT_MOC_LITERAL(14, 124, 13, 0),
QT_MOC_LITERAL(15, 138, 2, 0),
QT_MOC_LITERAL(16, 141, 2, 0),
QT_MOC_LITERAL(17, 144, 7, 0),
QT_MOC_LITERAL(18, 152, 33, 0),
QT_MOC_LITERAL(19, 186, 17, 0),
QT_MOC_LITERAL(20, 204, 22, 0),
QT_MOC_LITERAL(21, 227, 11, 0),
QT_MOC_LITERAL(22, 239, 16, 0)
    },
    "VideoInsertOcxLib::_DVideoInsertOcx\0exception\0\0code\0source\0disc\0help\0"
    "propertyChanged\0name\0signal\0argc\0argv\0AboutBox\0GetHWnd\0setWindowSize\0cx\0cy\0"
    "control\0VideoInsertOcxLib::VideoInsertOcx\0Event Interface 1\0_DVideoInsertOcxEvents\0"
    "Interface 0\0_DVideoInsertOcx\0"
};
#undef QT_MOC_LITERAL

static const uint qt_meta_data_VideoInsertOcxLib___DVideoInsertOcx[] = {

 // content:
    7, // revision
    0,  // classname
    0, 0, // classinfo
    6, 14, // methods
    1, 70, // properties
    0, 0, // enums/sets
    0, 0, // constructors
    0, // flags
    3, // signal count

// signal: name, argc, parameters, tag, flags
    1, 4, 44, 2, 5,
    7, 1, 53, 2, 5,
    9, 3, 56, 2, 5,

// slot: name, argc, parameters, tag, flags
    12, 0, 63, 2, 9,
    13, 0, 64, 2, 9,
    14, 2, 65, 2, 9,

// signal: parameters
    QMetaType::Void, QMetaType::Int, QMetaType::QString, QMetaType::QString, QMetaType::QString, 3, 4, 5, 6,
    QMetaType::Void, QMetaType::QString, 8,
    QMetaType::Void, QMetaType::QString, QMetaType::Int, QMetaType::VoidStar, 8, 10, 11,

// slot: parameters
    QMetaType::Void,
    QMetaType::Int,
    QMetaType::Int, QMetaType::Int, QMetaType::Int, 15, 16,

 // properties: name, type, flags
    17, QMetaType::QString, 0x0a055003, 		 // QString control

    0 // eod
};

const QMetaObject _DVideoInsertOcx::staticMetaObject = {
{ &QObject::staticMetaObject,
qt_meta_stringdata_all.data,
qt_meta_data_VideoInsertOcxLib___DVideoInsertOcx, 0, 0, 0 }
};

void *_DVideoInsertOcx::qt_metacast(const char *_clname)
{
    if (!_clname) return 0;
    if (!strcmp(_clname, "VideoInsertOcxLib::_DVideoInsertOcx"))
        return static_cast<void*>(const_cast<_DVideoInsertOcx*>(this));
    return QAxObject::qt_metacast(_clname);
}
static const uint qt_meta_data_VideoInsertOcxLib__VideoInsertOcx[] = {

 // content:
    7, // revision
    18,  // classname
    2, 14, // classinfo
    6, 18, // methods
    0, 0, // properties
    0, 0, // enums/sets
    0, 0, // constructors
    0, // flags
    3, // signal count

 // classinfo: key, value
    19, 20, 
    21, 22, 

// signal: name, argc, parameters, tag, flags
    1, 4, 48, 2, 5,
    7, 1, 57, 2, 5,
    9, 3, 60, 2, 5,

// slot: name, argc, parameters, tag, flags
    12, 0, 67, 2, 9,
    13, 0, 68, 2, 9,
    14, 2, 69, 2, 9,

// signal: parameters
    QMetaType::Void, QMetaType::Int, QMetaType::QString, QMetaType::QString, QMetaType::QString, 3, 4, 5, 6,
    QMetaType::Void, QMetaType::QString, 8,
    QMetaType::Void, QMetaType::QString, QMetaType::Int, QMetaType::VoidStar, 8, 10, 11,

// slot: parameters
    QMetaType::Void,
    QMetaType::Int,
    QMetaType::Int, QMetaType::Int, QMetaType::Int, 15, 16,

    0 // eod
};

const QMetaObject VideoInsertOcx::staticMetaObject = {
{ &QWidget::staticMetaObject,
qt_meta_stringdata_all.data,
qt_meta_data_VideoInsertOcxLib__VideoInsertOcx, 0, 0, 0 }
};

void *VideoInsertOcx::qt_metacast(const char *_clname)
{
    if (!_clname) return 0;
    if (!strcmp(_clname, "VideoInsertOcxLib::VideoInsertOcx"))
        return static_cast<void*>(const_cast<VideoInsertOcx*>(this));
    return QAxWidget::qt_metacast(_clname);
}

