/****************************************************************************
**
** Namespace VideoInsertOcxLib generated by dumpcpp v5.9.0 using
** dumpcpp.exe {4C178A86-3798-47A6-9617-D18CD613CC0C}
** from the type library C:\WINDOWS\SysWow64\VideoInsertOcx.ocx
**
****************************************************************************/

#ifndef QAX_DUMPCPP_VIDEOINSERTOCXLIB_H
#define QAX_DUMPCPP_VIDEOINSERTOCXLIB_H

// Define this symbol to __declspec(dllexport) or __declspec(dllimport)
#ifndef VIDEOINSERTOCXLIB_EXPORT
#define VIDEOINSERTOCXLIB_EXPORT
#endif

#include <qaxobject.h>
#include <qaxwidget.h>
#include <qdatetime.h>
#include <qpixmap.h>

struct IDispatch;


// Referenced namespace

namespace VideoInsertOcxLib {


class VIDEOINSERTOCXLIB_EXPORT _DVideoInsertOcx : public QAxObject
{
public:
    _DVideoInsertOcx(IDispatch *subobject = 0, QAxObject *parent = 0)
    : QAxObject((IUnknown*)subobject, parent)
    {
        internalRelease();
    }

    /*
    Method AboutBox

    For more information, see help context 0 in C:\WINDOWS\SysWow64\VideoInsertOcx.hlp.
    */
    inline void AboutBox();

    /*
    Method GetHWnd

    method GetHWnd
For more information, see help context 0 in C:\WINDOWS\SysWow64\VideoInsertOcx.hlp.
    */
    inline int GetHWnd();

    /*
    Method setWindowSize

    ·½·¨setWindowSize
For more information, see help context 0 in C:\WINDOWS\SysWow64\VideoInsertOcx.hlp.
    */
    inline int setWindowSize(int cx, int cy);

// meta object functions
    static const QMetaObject staticMetaObject;
    virtual const QMetaObject *metaObject() const { return &staticMetaObject; }
    virtual void *qt_metacast(const char *);
};

// skipping event interface _DVideoInsertOcxEvents

// Actual coclasses
class VIDEOINSERTOCXLIB_EXPORT VideoInsertOcx : public QAxWidget
{
public:
    VideoInsertOcx(QWidget *parent = 0, Qt::WindowFlags f = 0)
    : QAxWidget(parent, f)
    {
        setControl("{a7eac80d-9d73-4db9-9bff-68c8be0b6371}");
    }

    VideoInsertOcx(_DVideoInsertOcx *iface)
    : QAxWidget()
    {
        initializeFrom(iface);
        delete iface;
    }

    /*
    Method AboutBox

    For more information, see help context 0 in C:\WINDOWS\SysWow64\VideoInsertOcx.hlp.
    */
    inline void AboutBox();

    /*
    Method GetHWnd

    method GetHWnd
For more information, see help context 0 in C:\WINDOWS\SysWow64\VideoInsertOcx.hlp.
    */
    inline int GetHWnd();

    /*
    Method setWindowSize

    ????setWindowSize
For more information, see help context 0 in C:\WINDOWS\SysWow64\VideoInsertOcx.hlp.
    */
    inline int setWindowSize(int cx, int cy);

// meta object functions
    static const QMetaObject staticMetaObject;
    virtual const QMetaObject *metaObject() const { return &staticMetaObject; }
    virtual void *qt_metacast(const char *);
};

// member function implementation
#ifndef QAX_DUMPCPP_VIDEOINSERTOCXLIB_NOINLINES
inline void _DVideoInsertOcx::AboutBox()
{
    void *_a[] = {0};
    qt_metacall(QMetaObject::InvokeMetaMethod, 8, _a);
}

inline int _DVideoInsertOcx::GetHWnd()
{
    int qax_result;
    void *_a[] = {(void*)&qax_result};
    qt_metacall(QMetaObject::InvokeMetaMethod, 9, _a);
    return qax_result;
}

inline int _DVideoInsertOcx::setWindowSize(int cx, int cy)
{
    int qax_result;
    void *_a[] = {(void*)&qax_result, (void*)&cx, (void*)&cy};
    qt_metacall(QMetaObject::InvokeMetaMethod, 10, _a);
    return qax_result;
}


inline void VideoInsertOcx::AboutBox()
{
    void *_a[] = {0};
    qt_metacall(QMetaObject::InvokeMetaMethod, 35, _a);
}

inline int VideoInsertOcx::GetHWnd()
{
    int qax_result;
    void *_a[] = {(void*)&qax_result};
    qt_metacall(QMetaObject::InvokeMetaMethod, 36, _a);
    return qax_result;
}

inline int VideoInsertOcx::setWindowSize(int cx, int cy)
{
    int qax_result;
    void *_a[] = {(void*)&qax_result, (void*)&cx, (void*)&cy};
    qt_metacall(QMetaObject::InvokeMetaMethod, 37, _a);
    return qax_result;
}



#endif

}

QT_BEGIN_NAMESPACE

namespace QtMetaTypePrivate {
template<>
struct QMetaTypeFunctionHelper<VideoInsertOcxLib::_DVideoInsertOcx, /* Accepted */ true> {
    static void Destruct(void *t)
    {
        Q_UNUSED(t)
        static_cast<VideoInsertOcxLib::_DVideoInsertOcx*>(t)->VideoInsertOcxLib::_DVideoInsertOcx::~_DVideoInsertOcx();
    }
    static void *Construct(void *where, const void *t)
    {
        Q_ASSERT(!t);
        Q_UNUSED(t)
        return new (where) VideoInsertOcxLib::_DVideoInsertOcx;
    }
#ifndef QT_NO_DATASTREAM
    static void Save(QDataStream &stream, const void *t) { stream << *static_cast<const VideoInsertOcxLib::_DVideoInsertOcx*>(t); }
    static void Load(QDataStream &stream, void *t) { stream >> *static_cast<VideoInsertOcxLib::_DVideoInsertOcx*>(t); }
#endif // QT_NO_DATASTREAM
};

template<>
struct QMetaTypeFunctionHelper<VideoInsertOcxLib::VideoInsertOcx, /* Accepted */ true> {
    static void Destruct(void *t)
    {
        Q_UNUSED(t)
        static_cast<VideoInsertOcxLib::VideoInsertOcx*>(t)->VideoInsertOcxLib::VideoInsertOcx::~VideoInsertOcx();
    }
    static void *Construct(void *where, const void *t)
    {
        Q_ASSERT(!t);
        Q_UNUSED(t)
        return new (where) VideoInsertOcxLib::VideoInsertOcx;
    }
#ifndef QT_NO_DATASTREAM
    static void Save(QDataStream &stream, const void *t) { stream << *static_cast<const VideoInsertOcxLib::VideoInsertOcx*>(t); }
    static void Load(QDataStream &stream, void *t) { stream >> *static_cast<VideoInsertOcxLib::VideoInsertOcx*>(t); }
#endif // QT_NO_DATASTREAM
};

} // namespace QtMetaTypePrivate
QT_END_NAMESPACE

#endif

