/****************************************************************************
**
** Metadata for CmtVideoPlayerLib generated by dumpcpp v5.9.0 using
** dumpcpp.exe {0F12902B-28AB-4127-8070-931503B8EBA3}
** from the type library C:\Windows\SysWow64\CmtVideoPlayer.ocx
**
****************************************************************************/

#define QAX_DUMPCPP_CMTVIDEOPLAYERLIB_NOINLINES
#include "cmtvideoplayerlib.h"

using namespace CmtVideoPlayerLib;

struct qt_meta_stringdata_all_t {
    QByteArrayData data[23];
    char stringdata0[265];
};
#define QT_MOC_LITERAL(idx, ofs, len, table) \
    Q_STATIC_BYTE_ARRAY_DATA_HEADER_INITIALIZER_WITH_OFFSET(len, \
    offsetof(qt_meta_stringdata_all_t, stringdata##table) + ofs \
        - idx * sizeof(QByteArrayData) \
    )
static const qt_meta_stringdata_all_t qt_meta_stringdata_all = {
    {
QT_MOC_LITERAL(0, 0, 35, 0),
QT_MOC_LITERAL(1, 36, 9, 0),
QT_MOC_LITERAL(2, 46, 0, 0),
QT_MOC_LITERAL(3, 47, 4, 0),
QT_MOC_LITERAL(4, 52, 6, 0),
QT_MOC_LITERAL(5, 59, 4, 0),
QT_MOC_LITERAL(6, 64, 4, 0),
QT_MOC_LITERAL(7, 69, 15, 0),
QT_MOC_LITERAL(8, 85, 4, 0),
QT_MOC_LITERAL(9, 90, 6, 0),
QT_MOC_LITERAL(10, 97, 4, 0),
QT_MOC_LITERAL(11, 102, 4, 0),
QT_MOC_LITERAL(12, 107, 7, 0),
QT_MOC_LITERAL(13, 115, 10, 0),
QT_MOC_LITERAL(14, 126, 5, 0),
QT_MOC_LITERAL(15, 132, 7, 0),
QT_MOC_LITERAL(16, 140, 33, 0),
QT_MOC_LITERAL(17, 174, 17, 0),
QT_MOC_LITERAL(18, 192, 22, 0),
QT_MOC_LITERAL(19, 215, 11, 0),
QT_MOC_LITERAL(20, 227, 16, 0),
QT_MOC_LITERAL(21, 244, 10, 0),
QT_MOC_LITERAL(22, 255, 8, 0)
    },
    "CmtVideoPlayerLib::_DCmtVideoPlayer\0exception\0\0code\0source\0disc\0help\0"
    "propertyChanged\0name\0signal\0argc\0argv\0GetHWnd\0setVpIndex\0index\0control\0"
    "CmtVideoPlayerLib::CmtVideoPlayer\0Event Interface 1\0_DCmtVideoPlayerEvents\0"
    "Interface 0\0_DCmtVideoPlayer\0OnCtrEvent\0strEvent\0"
};
#undef QT_MOC_LITERAL

static const uint qt_meta_data_CmtVideoPlayerLib___DCmtVideoPlayer[] = {

 // content:
    7, // revision
    0,  // classname
    0, 0, // classinfo
    5, 14, // methods
    1, 62, // properties
    0, 0, // enums/sets
    0, 0, // constructors
    0, // flags
    3, // signal count

// signal: name, argc, parameters, tag, flags
    1, 4, 39, 2, 5,
    7, 1, 48, 2, 5,
    9, 3, 51, 2, 5,

// slot: name, argc, parameters, tag, flags
    12, 0, 58, 2, 9,
    13, 1, 59, 2, 9,

// signal: parameters
    QMetaType::Void, QMetaType::Int, QMetaType::QString, QMetaType::QString, QMetaType::QString, 3, 4, 5, 6,
    QMetaType::Void, QMetaType::QString, 8,
    QMetaType::Void, QMetaType::QString, QMetaType::Int, QMetaType::VoidStar, 8, 10, 11,

// slot: parameters
    QMetaType::Int,
    QMetaType::Void, QMetaType::Int, 14,

 // properties: name, type, flags
    15, QMetaType::QString, 0x0a055003, 		 // QString control

    0 // eod
};

const QMetaObject _DCmtVideoPlayer::staticMetaObject = {
{ &QObject::staticMetaObject,
qt_meta_stringdata_all.data,
qt_meta_data_CmtVideoPlayerLib___DCmtVideoPlayer, 0, 0, 0 }
};

void *_DCmtVideoPlayer::qt_metacast(const char *_clname)
{
    if (!_clname) return 0;
    if (!strcmp(_clname, "CmtVideoPlayerLib::_DCmtVideoPlayer"))
        return static_cast<void*>(const_cast<_DCmtVideoPlayer*>(this));
    return QAxObject::qt_metacast(_clname);
}
static const uint qt_meta_data_CmtVideoPlayerLib__CmtVideoPlayer[] = {

 // content:
    7, // revision
    16,  // classname
    2, 14, // classinfo
    6, 18, // methods
    0, 0, // properties
    0, 0, // enums/sets
    0, 0, // constructors
    0, // flags
    4, // signal count

 // classinfo: key, value
    17, 18, 
    19, 20, 

// signal: name, argc, parameters, tag, flags
    21, 1, 48, 2, 5,
    1, 4, 51, 2, 5,
    7, 1, 60, 2, 5,
    9, 3, 63, 2, 5,

// slot: name, argc, parameters, tag, flags
    12, 0, 70, 2, 9,
    13, 1, 71, 2, 9,

// signal: parameters
    QMetaType::Void, QMetaType::QString, 22,
    QMetaType::Void, QMetaType::Int, QMetaType::QString, QMetaType::QString, QMetaType::QString, 3, 4, 5, 6,
    QMetaType::Void, QMetaType::QString, 8,
    QMetaType::Void, QMetaType::QString, QMetaType::Int, QMetaType::VoidStar, 8, 10, 11,

// slot: parameters
    QMetaType::Int,
    QMetaType::Void, QMetaType::Int, 14,

    0 // eod
};

const QMetaObject CmtVideoPlayer::staticMetaObject = {
{ &QWidget::staticMetaObject,
qt_meta_stringdata_all.data,
qt_meta_data_CmtVideoPlayerLib__CmtVideoPlayer, 0, 0, 0 }
};

void *CmtVideoPlayer::qt_metacast(const char *_clname)
{
    if (!_clname) return 0;
    if (!strcmp(_clname, "CmtVideoPlayerLib::CmtVideoPlayer"))
        return static_cast<void*>(const_cast<CmtVideoPlayer*>(this));
    return QAxWidget::qt_metacast(_clname);
}

