/****************************************************************************
**
** Metadata for MultimediaScheduleOcxLib generated by dumpcpp v5.9.0 using
** dumpcpp.exe {8BAD5304-6F7B-4606-B1ED-31679DD8528B}
** from the type library C:\Windows\SysWow64\MultimediaScheduleOcx.ocx
**
****************************************************************************/

#define QAX_DUMPCPP_MULTIMEDIASCHEDULEOCXLIB_NOINLINES
#include "multimediascheduleocxlib.h"

using namespace MultimediaScheduleOcxLib;

struct qt_meta_stringdata_all_t {
    QByteArrayData data[177];
    char stringdata0[2291];
};
#define QT_MOC_LITERAL(idx, ofs, len, table) \
    Q_STATIC_BYTE_ARRAY_DATA_HEADER_INITIALIZER_WITH_OFFSET(len, \
    offsetof(qt_meta_stringdata_all_t, stringdata##table) + ofs \
        - idx * sizeof(QByteArrayData) \
    )
static const qt_meta_stringdata_all_t qt_meta_stringdata_all = {
    {
QT_MOC_LITERAL(0, 0, 49, 0),
QT_MOC_LITERAL(1, 50, 9, 0),
QT_MOC_LITERAL(2, 60, 0, 0),
QT_MOC_LITERAL(3, 61, 4, 0),
QT_MOC_LITERAL(4, 66, 6, 0),
QT_MOC_LITERAL(5, 73, 4, 0),
QT_MOC_LITERAL(6, 78, 4, 0),
QT_MOC_LITERAL(7, 83, 15, 0),
QT_MOC_LITERAL(8, 99, 4, 0),
QT_MOC_LITERAL(9, 104, 6, 0),
QT_MOC_LITERAL(10, 111, 4, 0),
QT_MOC_LITERAL(11, 116, 4, 0),
QT_MOC_LITERAL(12, 121, 8, 0),
QT_MOC_LITERAL(13, 130, 10, 0),
QT_MOC_LITERAL(14, 141, 6, 0),
QT_MOC_LITERAL(15, 148, 5, 0),
QT_MOC_LITERAL(16, 154, 18, 0),
QT_MOC_LITERAL(17, 173, 7, 0),
QT_MOC_LITERAL(18, 181, 9, 0),
QT_MOC_LITERAL(19, 191, 9, 0),
QT_MOC_LITERAL(20, 201, 18, 0),
QT_MOC_LITERAL(21, 220, 15, 0),
QT_MOC_LITERAL(22, 236, 7, 0),
QT_MOC_LITERAL(23, 244, 10, 0),
QT_MOC_LITERAL(24, 255, 20, 0),
QT_MOC_LITERAL(25, 276, 10, 0),
QT_MOC_LITERAL(26, 287, 8, 0),
QT_MOC_LITERAL(27, 296, 15, 0),
QT_MOC_LITERAL(28, 312, 17, 0),
QT_MOC_LITERAL(29, 330, 9, 0),
QT_MOC_LITERAL(30, 340, 5, 0),
QT_MOC_LITERAL(31, 346, 7, 0),
QT_MOC_LITERAL(32, 354, 12, 0),
QT_MOC_LITERAL(33, 367, 8, 0),
QT_MOC_LITERAL(34, 376, 15, 0),
QT_MOC_LITERAL(35, 392, 15, 0),
QT_MOC_LITERAL(36, 408, 13, 0),
QT_MOC_LITERAL(37, 422, 15, 0),
QT_MOC_LITERAL(38, 438, 17, 0),
QT_MOC_LITERAL(39, 456, 10, 0),
QT_MOC_LITERAL(40, 467, 6, 0),
QT_MOC_LITERAL(41, 474, 10, 0),
QT_MOC_LITERAL(42, 485, 12, 0),
QT_MOC_LITERAL(43, 498, 18, 0),
QT_MOC_LITERAL(44, 517, 15, 0),
QT_MOC_LITERAL(45, 533, 15, 0),
QT_MOC_LITERAL(46, 549, 13, 0),
QT_MOC_LITERAL(47, 563, 11, 0),
QT_MOC_LITERAL(48, 575, 19, 0),
QT_MOC_LITERAL(49, 595, 22, 0),
QT_MOC_LITERAL(50, 618, 10, 0),
QT_MOC_LITERAL(51, 629, 11, 0),
QT_MOC_LITERAL(52, 641, 10, 0),
QT_MOC_LITERAL(53, 652, 19, 0),
QT_MOC_LITERAL(54, 672, 13, 0),
QT_MOC_LITERAL(55, 686, 10, 0),
QT_MOC_LITERAL(56, 697, 21, 0),
QT_MOC_LITERAL(57, 719, 11, 0),
QT_MOC_LITERAL(58, 731, 4, 0),
QT_MOC_LITERAL(59, 736, 8, 0),
QT_MOC_LITERAL(60, 745, 4, 0),
QT_MOC_LITERAL(61, 750, 13, 0),
QT_MOC_LITERAL(62, 764, 4, 0),
QT_MOC_LITERAL(63, 769, 20, 0),
QT_MOC_LITERAL(64, 790, 17, 0),
QT_MOC_LITERAL(65, 808, 10, 0),
QT_MOC_LITERAL(66, 819, 6, 0),
QT_MOC_LITERAL(67, 826, 14, 0),
QT_MOC_LITERAL(68, 841, 6, 0),
QT_MOC_LITERAL(69, 848, 18, 0),
QT_MOC_LITERAL(70, 867, 11, 0),
QT_MOC_LITERAL(71, 879, 4, 0),
QT_MOC_LITERAL(72, 884, 3, 0),
QT_MOC_LITERAL(73, 888, 6, 0),
QT_MOC_LITERAL(74, 895, 4, 0),
QT_MOC_LITERAL(75, 900, 21, 0),
QT_MOC_LITERAL(76, 922, 5, 0),
QT_MOC_LITERAL(77, 928, 10, 0),
QT_MOC_LITERAL(78, 939, 3, 0),
QT_MOC_LITERAL(79, 943, 7, 0),
QT_MOC_LITERAL(80, 951, 10, 0),
QT_MOC_LITERAL(81, 962, 9, 0),
QT_MOC_LITERAL(82, 972, 9, 0),
QT_MOC_LITERAL(83, 982, 7, 0),
QT_MOC_LITERAL(84, 990, 19, 0),
QT_MOC_LITERAL(85, 1010, 4, 0),
QT_MOC_LITERAL(86, 1015, 6, 0),
QT_MOC_LITERAL(87, 1022, 6, 0),
QT_MOC_LITERAL(88, 1029, 13, 0),
QT_MOC_LITERAL(89, 1043, 3, 0),
QT_MOC_LITERAL(90, 1047, 5, 0),
QT_MOC_LITERAL(91, 1053, 7, 0),
QT_MOC_LITERAL(92, 1061, 5, 0),
QT_MOC_LITERAL(93, 1067, 9, 0),
QT_MOC_LITERAL(94, 1077, 3, 0),
QT_MOC_LITERAL(95, 1081, 16, 0),
QT_MOC_LITERAL(96, 1098, 15, 0),
QT_MOC_LITERAL(97, 1114, 15, 0),
QT_MOC_LITERAL(98, 1130, 14, 0),
QT_MOC_LITERAL(99, 1145, 15, 0),
QT_MOC_LITERAL(100, 1161, 8, 0),
QT_MOC_LITERAL(101, 1170, 12, 0),
QT_MOC_LITERAL(102, 1183, 13, 0),
QT_MOC_LITERAL(103, 1197, 7, 0),
QT_MOC_LITERAL(104, 1205, 9, 0),
QT_MOC_LITERAL(105, 1215, 18, 0),
QT_MOC_LITERAL(106, 1234, 6, 0),
QT_MOC_LITERAL(107, 1241, 7, 0),
QT_MOC_LITERAL(108, 1249, 14, 0),
QT_MOC_LITERAL(109, 1264, 10, 0),
QT_MOC_LITERAL(110, 1275, 16, 0),
QT_MOC_LITERAL(111, 1292, 7, 0),
QT_MOC_LITERAL(112, 1300, 6, 0),
QT_MOC_LITERAL(113, 1307, 11, 0),
QT_MOC_LITERAL(114, 1319, 18, 0),
QT_MOC_LITERAL(115, 1338, 9, 0),
QT_MOC_LITERAL(116, 1348, 10, 0),
QT_MOC_LITERAL(117, 1359, 16, 0),
QT_MOC_LITERAL(118, 1376, 11, 0),
QT_MOC_LITERAL(119, 1388, 17, 0),
QT_MOC_LITERAL(120, 1406, 11, 0),
QT_MOC_LITERAL(121, 1418, 15, 0),
QT_MOC_LITERAL(122, 1434, 24, 0),
QT_MOC_LITERAL(123, 1459, 18, 0),
QT_MOC_LITERAL(124, 1478, 6, 0),
QT_MOC_LITERAL(125, 1485, 11, 0),
QT_MOC_LITERAL(126, 1497, 16, 0),
QT_MOC_LITERAL(127, 1514, 13, 0),
QT_MOC_LITERAL(128, 1528, 18, 0),
QT_MOC_LITERAL(129, 1547, 18, 0),
QT_MOC_LITERAL(130, 1566, 18, 0),
QT_MOC_LITERAL(131, 1585, 9, 0),
QT_MOC_LITERAL(132, 1595, 7, 0),
QT_MOC_LITERAL(133, 1603, 47, 0),
QT_MOC_LITERAL(134, 1651, 17, 0),
QT_MOC_LITERAL(135, 1669, 29, 0),
QT_MOC_LITERAL(136, 1699, 11, 0),
QT_MOC_LITERAL(137, 1711, 23, 0),
QT_MOC_LITERAL(138, 1735, 20, 0),
QT_MOC_LITERAL(139, 1756, 12, 0),
QT_MOC_LITERAL(140, 1769, 10, 0),
QT_MOC_LITERAL(141, 1780, 10, 0),
QT_MOC_LITERAL(142, 1791, 21, 0),
QT_MOC_LITERAL(143, 1813, 16, 0),
QT_MOC_LITERAL(144, 1830, 19, 0),
QT_MOC_LITERAL(145, 1850, 17, 0),
QT_MOC_LITERAL(146, 1868, 24, 0),
QT_MOC_LITERAL(147, 1893, 6, 0),
QT_MOC_LITERAL(148, 1900, 19, 0),
QT_MOC_LITERAL(149, 1920, 8, 0),
QT_MOC_LITERAL(150, 1929, 13, 0),
QT_MOC_LITERAL(151, 1943, 6, 0),
QT_MOC_LITERAL(152, 1950, 9, 0),
QT_MOC_LITERAL(153, 1960, 6, 0),
QT_MOC_LITERAL(154, 1967, 15, 0),
QT_MOC_LITERAL(155, 1983, 6, 0),
QT_MOC_LITERAL(156, 1990, 10, 0),
QT_MOC_LITERAL(157, 2001, 8, 0),
QT_MOC_LITERAL(158, 2010, 4, 0),
QT_MOC_LITERAL(159, 2015, 19, 0),
QT_MOC_LITERAL(160, 2035, 14, 0),
QT_MOC_LITERAL(161, 2050, 4, 0),
QT_MOC_LITERAL(162, 2055, 7, 0),
QT_MOC_LITERAL(163, 2063, 8, 0),
QT_MOC_LITERAL(164, 2072, 17, 0),
QT_MOC_LITERAL(165, 2090, 14, 0),
QT_MOC_LITERAL(166, 2105, 20, 0),
QT_MOC_LITERAL(167, 2126, 19, 0),
QT_MOC_LITERAL(168, 2146, 18, 0),
QT_MOC_LITERAL(169, 2165, 8, 0),
QT_MOC_LITERAL(170, 2174, 24, 0),
QT_MOC_LITERAL(171, 2199, 9, 0),
QT_MOC_LITERAL(172, 2209, 23, 0),
QT_MOC_LITERAL(173, 2233, 6, 0),
QT_MOC_LITERAL(174, 2240, 6, 0),
QT_MOC_LITERAL(175, 2247, 20, 0),
QT_MOC_LITERAL(176, 2268, 21, 0)
    },
    "MultimediaScheduleOcxLib::_DMultimediaScheduleOcx\0exception\0\0code\0source\0"
    "disc\0help\0propertyChanged\0name\0signal\0argc\0argv\0AboutBox\0answerCall\0callId\0"
    "nHand\0audioMeetAddMember\0wint_t*\0strMeetID\0memberSip\0audioMeetDelMember\0"
    "callThroughConn\0nCallId\0strDestSip\0createAudioBroadcast\0strMembers\0filePath\0"
    "createAudioMeet\0createPttGroupURL\0strServer\0nPort\0groupID\0strGroupName\0"
    "strMySip\0createVideoMeet\0delTempPttGroup\0strBigGroupID\0strSmallGroupID\0"
    "deletePttGroupURL\0destroyOcx\0endPtt\0csGroupNum\0endVideoMeet\0getAudioDeviceList\0"
    "getCurrentGroup\0getDefaultGroup\0getGroupState\0pttGroupNum\0getPhysicsHandCount\0"
    "getPttGroupMemberState\0strGroupID\0strMemberID\0hangUpCall\0isVideoConversation\0"
    "makeAudioCall\0destNumber\0makeAudioCallWithFile\0makePttCall\0dest\0audioDev\0"
    "join\0makeVideoCall\0hWnd\0makeVideoMonitorCall\0modifyPttGroupURL\0ptzControl\0"
    "strSIP\0strControlType\0isDown\0queryVideoDispatch\0registerSip\0user\0pwd\0server\0"
    "port\0remoteControlLocation\0bOpen\0requestPtt\0opt\0sendSMS\0strContent\0sendSmsEx\0"
    "extension\0strType\0setAudioDeviceIndex\0type\0sIndex\0mIndex\0setConfigInfo\0key\0"
    "value\0setMute\0bMute\0setMuteEx\0bRx\0setPreviewWindow\0setTempPttGroup\0strLargeGroupNo\0"
    "strGroupMember\0setVideoBitRate\0nBitRate\0setVideoInfo\0nDropeedFrame\0nBuffer\0"
    "nPlayMode\0setVideoResolution\0nWidth\0nHeight\0setVideoRotate\0bClockWise\0"
    "setVideoTransmit\0call_id\0txFlag\0setVideoWnd\0startVideoDispatch\0strSrcNum\0"
    "strDestNum\0startVideoRecord\0strFileName\0stopVideoDispatch\0strChanName\0"
    "stopVideoRecord\0subscribeAllPttGroupInfo\0subscribeUserState\0number\0switchGroup\0"
    "takeVideoPicture\0unregisterSip\0videoMeetAddMember\0videoMeetDelMember\0"
    "videoMeetPlayVideo\0strSipNum\0control\0MultimediaScheduleOcxLib::MultimediaScheduleOcx\0"
    "Event Interface 1\0_DMultimediaScheduleOcxEvents\0Interface 0\0_DMultimediaScheduleOcx\0"
    "onEventAudioMeetJoin\0strActionSip\0strUserNum\0bAdminFlag\0onEventAudioMeetLeave\0"
    "onEventConnected\0onEventDisconnected\0onEventFileRecord\0onEventGooseneckMicClick\0"
    "nState\0onEventIncomingCall\0typeInfo\0onEventKeyPad\0iDevId\0keyNumber\0bKeyUp\0"
    "onEventPttGroup\0nEvent\0strIDGroup\0strGroup\0bDel\0onEventPttTempGroup\0"
    "onEventRecvSMS\0from\0content\0groupMem\0onEventRegistered\0onEventRinging\0"
    "onEventSmsGeneralCmd\0onEventStateNetWork\0onEventSwitchGroup\0bSuccess\0"
    "onEventURLPttGroupNotify\0strNotify\0onEventUserStatusUpdate\0sipNum\0status\0"
    "onEventVideoMeetJoin\0onEventVideoMeetLeave\0"
};
#undef QT_MOC_LITERAL

static const uint qt_meta_data_MultimediaScheduleOcxLib___DMultimediaScheduleOcx[] = {

 // content:
    7, // revision
    0,  // classname
    0, 0, // classinfo
    62, 14, // methods
    1, 626, // properties
    0, 0, // enums/sets
    0, 0, // constructors
    0, // flags
    3, // signal count

// signal: name, argc, parameters, tag, flags
    1, 4, 324, 2, 5,
    7, 1, 333, 2, 5,
    9, 3, 336, 2, 5,

// slot: name, argc, parameters, tag, flags
    12, 0, 343, 2, 9,
    13, 2, 344, 2, 9,
    16, 2, 349, 2, 9,
    20, 2, 354, 2, 9,
    21, 2, 359, 2, 9,
    24, 3, 364, 2, 9,
    27, 2, 371, 2, 9,
    28, 6, 376, 2, 9,
    34, 2, 389, 2, 9,
    35, 2, 394, 2, 9,
    38, 3, 399, 2, 9,
    39, 0, 406, 2, 9,
    40, 1, 407, 2, 9,
    42, 1, 410, 2, 9,
    43, 0, 413, 2, 9,
    44, 0, 414, 2, 9,
    45, 0, 415, 2, 9,
    46, 1, 416, 2, 9,
    48, 0, 419, 2, 9,
    49, 2, 420, 2, 9,
    52, 1, 425, 2, 9,
    53, 1, 428, 2, 9,
    54, 2, 431, 2, 9,
    56, 2, 436, 2, 9,
    57, 3, 441, 2, 9,
    61, 3, 448, 2, 9,
    63, 2, 455, 2, 9,
    64, 6, 460, 2, 9,
    65, 3, 473, 2, 9,
    69, 0, 480, 2, 9,
    70, 4, 481, 2, 9,
    75, 2, 490, 2, 9,
    77, 1, 495, 2, 9,
    79, 2, 498, 2, 9,
    81, 4, 503, 2, 9,
    84, 3, 512, 2, 9,
    88, 2, 519, 2, 9,
    91, 2, 524, 2, 9,
    93, 3, 529, 2, 9,
    95, 1, 536, 2, 9,
    96, 3, 539, 2, 9,
    99, 1, 546, 2, 9,
    101, 3, 549, 2, 9,
    105, 2, 556, 2, 9,
    108, 2, 561, 2, 9,
    110, 2, 566, 2, 9,
    113, 2, 571, 2, 9,
    114, 2, 576, 2, 9,
    117, 2, 581, 2, 9,
    119, 2, 586, 2, 9,
    121, 1, 591, 2, 9,
    122, 0, 594, 2, 9,
    123, 2, 595, 2, 9,
    125, 1, 600, 2, 9,
    126, 2, 603, 2, 9,
    127, 0, 608, 2, 9,
    128, 2, 609, 2, 9,
    129, 2, 614, 2, 9,
    130, 3, 619, 2, 9,

// signal: parameters
    QMetaType::Void, QMetaType::Int, QMetaType::QString, QMetaType::QString, QMetaType::QString, 3, 4, 5, 6,
    QMetaType::Void, QMetaType::QString, 8,
    QMetaType::Void, QMetaType::QString, QMetaType::Int, QMetaType::VoidStar, 8, 10, 11,

// slot: parameters
    QMetaType::Void,
    QMetaType::Int, QMetaType::Int, QMetaType::Int, 14, 15,
    QMetaType::Int, 0x80000000 | 17, 0x80000000 | 17, 18, 19,
    QMetaType::Int, 0x80000000 | 17, 0x80000000 | 17, 18, 19,
    QMetaType::Void, QMetaType::Int, 0x80000000 | 17, 22, 23,
    QMetaType::Int, QMetaType::QString, QMetaType::Int, QMetaType::QString, 25, 15, 26,
    QMetaType::Int, 0x80000000 | 17, QMetaType::Int, 25, 15,
    QMetaType::Void, 0x80000000 | 17, QMetaType::Int, 0x80000000 | 17, 0x80000000 | 17, 0x80000000 | 17, 0x80000000 | 17, 29, 30, 31, 32, 33, 25,
    QMetaType::Int, 0x80000000 | 17, QMetaType::Int, 19, 15,
    QMetaType::Void, 0x80000000 | 17, 0x80000000 | 17, 36, 37,
    QMetaType::Void, 0x80000000 | 17, QMetaType::Int, 0x80000000 | 17, 29, 30, 31,
    QMetaType::Void,
    QMetaType::Void, 0x80000000 | 17, 41,
    QMetaType::Int, QMetaType::Int, 22,
    QMetaType::QString,
    QMetaType::QString,
    QMetaType::QString,
    QMetaType::Int, 0x80000000 | 17, 47,
    QMetaType::Int,
    QMetaType::Int, 0x80000000 | 17, 0x80000000 | 17, 50, 51,
    QMetaType::Int, QMetaType::Int, 14,
    QMetaType::Int, QMetaType::Int, 14,
    QMetaType::Int, QMetaType::QString, QMetaType::Int, 55, 15,
    QMetaType::Int, QMetaType::QString, QMetaType::QString, 55, 26,
    QMetaType::Int, 0x80000000 | 17, QMetaType::Int, QMetaType::Int, 58, 59, 60,
    QMetaType::Int, QMetaType::QString, QMetaType::Int, QMetaType::Int, 55, 62, 15,
    QMetaType::Int, QMetaType::QString, QMetaType::Int, 55, 15,
    QMetaType::Void, 0x80000000 | 17, QMetaType::Int, 0x80000000 | 17, 0x80000000 | 17, 0x80000000 | 17, 0x80000000 | 17, 29, 30, 31, 32, 33, 25,
    QMetaType::Void, 0x80000000 | 17, 0x80000000 | 17, QMetaType::Bool, 66, 67, 68,
    QMetaType::QString,
    QMetaType::Int, QMetaType::QString, QMetaType::QString, QMetaType::QString, QMetaType::Int, 71, 72, 73, 74,
    QMetaType::Int, 0x80000000 | 17, QMetaType::Bool, 23, 76,
    QMetaType::Void, QMetaType::Int, 78,
    QMetaType::Int, QMetaType::QString, QMetaType::QString, 66, 80,
    QMetaType::Int, QMetaType::QString, QMetaType::QString, QMetaType::QString, QMetaType::QString, 66, 80, 82, 83,
    QMetaType::Int, QMetaType::Int, QMetaType::Int, QMetaType::Int, 85, 86, 87,
    QMetaType::Int, QMetaType::QString, QMetaType::QString, 89, 90,
    QMetaType::Int, QMetaType::Int, QMetaType::Bool, 14, 92,
    QMetaType::Int, QMetaType::Int, QMetaType::Bool, QMetaType::Bool, 14, 94, 92,
    QMetaType::UInt, QMetaType::UInt, 62,
    QMetaType::Void, 0x80000000 | 17, 0x80000000 | 17, 0x80000000 | 17, 97, 32, 98,
    QMetaType::Int, QMetaType::Int, 100,
    QMetaType::Int, QMetaType::Int, QMetaType::Int, QMetaType::Int, 102, 103, 104,
    QMetaType::Int, QMetaType::Int, QMetaType::Int, 106, 107,
    QMetaType::Void, QMetaType::Int, QMetaType::Bool, 14, 109,
    QMetaType::Void, QMetaType::Int, QMetaType::Int, 111, 112,
    QMetaType::Int, QMetaType::Int, QMetaType::Int, 14, 62,
    QMetaType::Void, 0x80000000 | 17, 0x80000000 | 17, 115, 116,
    QMetaType::Int, QMetaType::QString, QMetaType::Int, 118, 14,
    QMetaType::Void, 0x80000000 | 17, 0x80000000 | 17, 120, 116,
    QMetaType::Void, QMetaType::Int, 14,
    QMetaType::Void,
    QMetaType::Int, QMetaType::QString, QMetaType::Int, 124, 85,
    QMetaType::Void, 0x80000000 | 17, 41,
    QMetaType::Int, QMetaType::QString, QMetaType::Int, 118, 14,
    QMetaType::Void,
    QMetaType::Int, 0x80000000 | 17, 0x80000000 | 17, 18, 19,
    QMetaType::Int, 0x80000000 | 17, 0x80000000 | 17, 18, 19,
    QMetaType::Int, QMetaType::Int, QMetaType::Int, 0x80000000 | 17, 62, 22, 131,

 // properties: name, type, flags
    132, QMetaType::QString, 0x0a055003, 		 // QString control

    0 // eod
};

const QMetaObject _DMultimediaScheduleOcx::staticMetaObject = {
{ &QObject::staticMetaObject,
qt_meta_stringdata_all.data,
qt_meta_data_MultimediaScheduleOcxLib___DMultimediaScheduleOcx, 0, 0, 0 }
};

void *_DMultimediaScheduleOcx::qt_metacast(const char *_clname)
{
    if (!_clname) return 0;
    if (!strcmp(_clname, "MultimediaScheduleOcxLib::_DMultimediaScheduleOcx"))
        return static_cast<void*>(const_cast<_DMultimediaScheduleOcx*>(this));
    return QAxObject::qt_metacast(_clname);
}
static const uint qt_meta_data_MultimediaScheduleOcxLib__MultimediaScheduleOcx[] = {

 // content:
    7, // revision
    133,  // classname
    2, 14, // classinfo
    82, 18, // methods
    0, 0, // properties
    0, 0, // enums/sets
    0, 0, // constructors
    0, // flags
    23, // signal count

 // classinfo: key, value
    134, 135, 
    136, 137, 

// signal: name, argc, parameters, tag, flags
    1, 4, 428, 2, 5,
    138, 4, 437, 2, 5,
    142, 2, 446, 2, 5,
    143, 1, 451, 2, 5,
    144, 1, 454, 2, 5,
    145, 1, 457, 2, 5,
    146, 1, 460, 2, 5,
    148, 3, 463, 2, 5,
    150, 3, 470, 2, 5,
    154, 4, 477, 2, 5,
    159, 3, 486, 2, 5,
    160, 5, 493, 2, 5,
    164, 1, 504, 2, 5,
    165, 1, 507, 2, 5,
    166, 3, 510, 2, 5,
    167, 1, 517, 2, 5,
    168, 2, 520, 2, 5,
    170, 1, 525, 2, 5,
    172, 2, 528, 2, 5,
    175, 4, 533, 2, 5,
    176, 2, 542, 2, 5,
    7, 1, 547, 2, 5,
    9, 3, 550, 2, 5,

// slot: name, argc, parameters, tag, flags
    12, 0, 557, 2, 9,
    13, 2, 558, 2, 9,
    16, 2, 563, 2, 9,
    20, 2, 568, 2, 9,
    21, 2, 573, 2, 9,
    24, 3, 578, 2, 9,
    27, 2, 585, 2, 9,
    28, 6, 590, 2, 9,
    34, 2, 603, 2, 9,
    35, 2, 608, 2, 9,
    38, 3, 613, 2, 9,
    39, 0, 620, 2, 9,
    40, 1, 621, 2, 9,
    42, 1, 624, 2, 9,
    43, 0, 627, 2, 9,
    44, 0, 628, 2, 9,
    45, 0, 629, 2, 9,
    46, 1, 630, 2, 9,
    48, 0, 633, 2, 9,
    49, 2, 634, 2, 9,
    52, 1, 639, 2, 9,
    53, 1, 642, 2, 9,
    54, 2, 645, 2, 9,
    56, 2, 650, 2, 9,
    57, 3, 655, 2, 9,
    61, 3, 662, 2, 9,
    63, 2, 669, 2, 9,
    64, 6, 674, 2, 9,
    65, 3, 687, 2, 9,
    69, 0, 694, 2, 9,
    70, 4, 695, 2, 9,
    75, 2, 704, 2, 9,
    77, 1, 709, 2, 9,
    79, 2, 712, 2, 9,
    81, 4, 717, 2, 9,
    84, 3, 726, 2, 9,
    88, 2, 733, 2, 9,
    91, 2, 738, 2, 9,
    93, 3, 743, 2, 9,
    95, 1, 750, 2, 9,
    96, 3, 753, 2, 9,
    99, 1, 760, 2, 9,
    101, 3, 763, 2, 9,
    105, 2, 770, 2, 9,
    108, 2, 775, 2, 9,
    110, 2, 780, 2, 9,
    113, 2, 785, 2, 9,
    114, 2, 790, 2, 9,
    117, 2, 795, 2, 9,
    119, 2, 800, 2, 9,
    121, 1, 805, 2, 9,
    122, 0, 808, 2, 9,
    123, 2, 809, 2, 9,
    125, 1, 814, 2, 9,
    126, 2, 817, 2, 9,
    127, 0, 822, 2, 9,
    128, 2, 823, 2, 9,
    129, 2, 828, 2, 9,
    130, 3, 833, 2, 9,

// signal: parameters
    QMetaType::Void, QMetaType::Int, QMetaType::QString, QMetaType::QString, QMetaType::QString, 3, 4, 5, 6,
    QMetaType::Void, QMetaType::QString, QMetaType::QString, QMetaType::QString, QMetaType::Int, 18, 139, 140, 141,
    QMetaType::Void, QMetaType::QString, QMetaType::QString, 18, 139,
    QMetaType::Void, QMetaType::Int, 14,
    QMetaType::Void, QMetaType::Int, 14,
    QMetaType::Void, QMetaType::QString, 118,
    QMetaType::Void, QMetaType::Int, 147,
    QMetaType::Void, QMetaType::QString, QMetaType::Int, QMetaType::QString, 55, 14, 149,
    QMetaType::Void, QMetaType::Int, QMetaType::Int, QMetaType::Int, 151, 152, 153,
    QMetaType::Void, QMetaType::Int, QMetaType::QString, QMetaType::QString, QMetaType::Bool, 155, 156, 157, 158,
    QMetaType::Void, QMetaType::Int, QMetaType::QString, QMetaType::QString, 155, 156, 157,
    QMetaType::Void, QMetaType::QString, QMetaType::QString, QMetaType::QString, QMetaType::QString, QMetaType::QString, 161, 162, 83, 163, 82,
    QMetaType::Void, QMetaType::Int, 3,
    QMetaType::Void, QMetaType::Int, 14,
    QMetaType::Void, QMetaType::QString, QMetaType::QString, QMetaType::QString, 161, 83, 80,
    QMetaType::Void, QMetaType::Int, 147,
    QMetaType::Void, QMetaType::QString, QMetaType::Int, 156, 169,
    QMetaType::Void, QMetaType::QString, 171,
    QMetaType::Void, QMetaType::QString, QMetaType::Int, 173, 174,
    QMetaType::Void, QMetaType::QString, QMetaType::QString, QMetaType::QString, QMetaType::Int, 18, 139, 140, 141,
    QMetaType::Void, QMetaType::QString, QMetaType::QString, 18, 139,
    QMetaType::Void, QMetaType::QString, 8,
    QMetaType::Void, QMetaType::QString, QMetaType::Int, QMetaType::VoidStar, 8, 10, 11,

// slot: parameters
    QMetaType::Void,
    QMetaType::Int, QMetaType::Int, QMetaType::Int, 14, 15,
    QMetaType::Int, 0x80000000 | 17, 0x80000000 | 17, 18, 19,
    QMetaType::Int, 0x80000000 | 17, 0x80000000 | 17, 18, 19,
    QMetaType::Void, QMetaType::Int, 0x80000000 | 17, 22, 23,
    QMetaType::Int, QMetaType::QString, QMetaType::Int, QMetaType::QString, 25, 15, 26,
    QMetaType::Int, 0x80000000 | 17, QMetaType::Int, 25, 15,
    QMetaType::Void, 0x80000000 | 17, QMetaType::Int, 0x80000000 | 17, 0x80000000 | 17, 0x80000000 | 17, 0x80000000 | 17, 29, 30, 31, 32, 33, 25,
    QMetaType::Int, 0x80000000 | 17, QMetaType::Int, 19, 15,
    QMetaType::Void, 0x80000000 | 17, 0x80000000 | 17, 36, 37,
    QMetaType::Void, 0x80000000 | 17, QMetaType::Int, 0x80000000 | 17, 29, 30, 31,
    QMetaType::Void,
    QMetaType::Void, 0x80000000 | 17, 41,
    QMetaType::Int, QMetaType::Int, 22,
    QMetaType::QString,
    QMetaType::QString,
    QMetaType::QString,
    QMetaType::Int, 0x80000000 | 17, 47,
    QMetaType::Int,
    QMetaType::Int, 0x80000000 | 17, 0x80000000 | 17, 50, 51,
    QMetaType::Int, QMetaType::Int, 14,
    QMetaType::Int, QMetaType::Int, 14,
    QMetaType::Int, QMetaType::QString, QMetaType::Int, 55, 15,
    QMetaType::Int, QMetaType::QString, QMetaType::QString, 55, 26,
    QMetaType::Int, 0x80000000 | 17, QMetaType::Int, QMetaType::Int, 58, 59, 60,
    QMetaType::Int, QMetaType::QString, QMetaType::Int, QMetaType::Int, 55, 62, 15,
    QMetaType::Int, QMetaType::QString, QMetaType::Int, 55, 15,
    QMetaType::Void, 0x80000000 | 17, QMetaType::Int, 0x80000000 | 17, 0x80000000 | 17, 0x80000000 | 17, 0x80000000 | 17, 29, 30, 31, 32, 33, 25,
    QMetaType::Void, 0x80000000 | 17, 0x80000000 | 17, QMetaType::Bool, 66, 67, 68,
    QMetaType::QString,
    QMetaType::Int, QMetaType::QString, QMetaType::QString, QMetaType::QString, QMetaType::Int, 71, 72, 73, 74,
    QMetaType::Int, 0x80000000 | 17, QMetaType::Bool, 23, 76,
    QMetaType::Void, QMetaType::Int, 78,
    QMetaType::Int, QMetaType::QString, QMetaType::QString, 66, 80,
    QMetaType::Int, QMetaType::QString, QMetaType::QString, QMetaType::QString, QMetaType::QString, 66, 80, 82, 83,
    QMetaType::Int, QMetaType::Int, QMetaType::Int, QMetaType::Int, 85, 86, 87,
    QMetaType::Int, QMetaType::QString, QMetaType::QString, 89, 90,
    QMetaType::Int, QMetaType::Int, QMetaType::Bool, 14, 92,
    QMetaType::Int, QMetaType::Int, QMetaType::Bool, QMetaType::Bool, 14, 94, 92,
    QMetaType::UInt, QMetaType::UInt, 62,
    QMetaType::Void, 0x80000000 | 17, 0x80000000 | 17, 0x80000000 | 17, 97, 32, 98,
    QMetaType::Int, QMetaType::Int, 100,
    QMetaType::Int, QMetaType::Int, QMetaType::Int, QMetaType::Int, 102, 103, 104,
    QMetaType::Int, QMetaType::Int, QMetaType::Int, 106, 107,
    QMetaType::Void, QMetaType::Int, QMetaType::Bool, 14, 109,
    QMetaType::Void, QMetaType::Int, QMetaType::Int, 111, 112,
    QMetaType::Int, QMetaType::Int, QMetaType::Int, 14, 62,
    QMetaType::Void, 0x80000000 | 17, 0x80000000 | 17, 115, 116,
    QMetaType::Int, QMetaType::QString, QMetaType::Int, 118, 14,
    QMetaType::Void, 0x80000000 | 17, 0x80000000 | 17, 120, 116,
    QMetaType::Void, QMetaType::Int, 14,
    QMetaType::Void,
    QMetaType::Int, QMetaType::QString, QMetaType::Int, 124, 85,
    QMetaType::Void, 0x80000000 | 17, 41,
    QMetaType::Int, QMetaType::QString, QMetaType::Int, 118, 14,
    QMetaType::Void,
    QMetaType::Int, 0x80000000 | 17, 0x80000000 | 17, 18, 19,
    QMetaType::Int, 0x80000000 | 17, 0x80000000 | 17, 18, 19,
    QMetaType::Int, QMetaType::Int, QMetaType::Int, 0x80000000 | 17, 62, 22, 131,

    0 // eod
};

const QMetaObject MultimediaScheduleOcx::staticMetaObject = {
{ &QWidget::staticMetaObject,
qt_meta_stringdata_all.data,
qt_meta_data_MultimediaScheduleOcxLib__MultimediaScheduleOcx, 0, 0, 0 }
};

void *MultimediaScheduleOcx::qt_metacast(const char *_clname)
{
    if (!_clname) return 0;
    if (!strcmp(_clname, "MultimediaScheduleOcxLib::MultimediaScheduleOcx"))
        return static_cast<void*>(const_cast<MultimediaScheduleOcx*>(this));
    return QAxWidget::qt_metacast(_clname);
}

